/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedPaymentMethodsRouteImport } from './routes/_authenticated/payment-methods'
import { Route as AuthenticatedPaymentDetailsRouteImport } from './routes/_authenticated/payment-details'
import { Route as AuthenticatedPaymentCorrectionsRouteImport } from './routes/_authenticated/payment-corrections'
import { Route as AuthenticatedPackagesRouteImport } from './routes/_authenticated/packages'
import { Route as AuthenticatedMyBillsRouteImport } from './routes/_authenticated/my-bills'
import { Route as AuthenticatedDealersRouteImport } from './routes/_authenticated/dealers'
import { Route as AuthenticatedAreasRouteImport } from './routes/_authenticated/areas'
import { Route as AuthenticatedAdvertisementsRouteImport } from './routes/_authenticated/advertisements'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardAreaAreaIdRouteImport } from './routes/_authenticated/dashboard/area.$areaId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPaymentMethodsRoute =
  AuthenticatedPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentDetailsRoute =
  AuthenticatedPaymentDetailsRouteImport.update({
    id: '/payment-details',
    path: '/payment-details',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentCorrectionsRoute =
  AuthenticatedPaymentCorrectionsRouteImport.update({
    id: '/payment-corrections',
    path: '/payment-corrections',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPackagesRoute = AuthenticatedPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyBillsRoute = AuthenticatedMyBillsRouteImport.update({
  id: '/my-bills',
  path: '/my-bills',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDealersRoute = AuthenticatedDealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAreasRoute = AuthenticatedAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdvertisementsRoute =
  AuthenticatedAdvertisementsRouteImport.update({
    id: '/advertisements',
    path: '/advertisements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAreaAreaIdRoute =
  AuthenticatedDashboardAreaAreaIdRouteImport.update({
    id: '/dashboard/area/$areaId',
    path: '/dashboard/area/$areaId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/advertisements': typeof AuthenticatedAdvertisementsRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/dealers': typeof AuthenticatedDealersRoute
  '/my-bills': typeof AuthenticatedMyBillsRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/payment-corrections': typeof AuthenticatedPaymentCorrectionsRoute
  '/payment-details': typeof AuthenticatedPaymentDetailsRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/area/$areaId': typeof AuthenticatedDashboardAreaAreaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/advertisements': typeof AuthenticatedAdvertisementsRoute
  '/areas': typeof AuthenticatedAreasRoute
  '/dealers': typeof AuthenticatedDealersRoute
  '/my-bills': typeof AuthenticatedMyBillsRoute
  '/packages': typeof AuthenticatedPackagesRoute
  '/payment-corrections': typeof AuthenticatedPaymentCorrectionsRoute
  '/payment-details': typeof AuthenticatedPaymentDetailsRoute
  '/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/area/$areaId': typeof AuthenticatedDashboardAreaAreaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/advertisements': typeof AuthenticatedAdvertisementsRoute
  '/_authenticated/areas': typeof AuthenticatedAreasRoute
  '/_authenticated/dealers': typeof AuthenticatedDealersRoute
  '/_authenticated/my-bills': typeof AuthenticatedMyBillsRoute
  '/_authenticated/packages': typeof AuthenticatedPackagesRoute
  '/_authenticated/payment-corrections': typeof AuthenticatedPaymentCorrectionsRoute
  '/_authenticated/payment-details': typeof AuthenticatedPaymentDetailsRoute
  '/_authenticated/payment-methods': typeof AuthenticatedPaymentMethodsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/area/$areaId': typeof AuthenticatedDashboardAreaAreaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/advertisements'
    | '/areas'
    | '/dealers'
    | '/my-bills'
    | '/packages'
    | '/payment-corrections'
    | '/payment-details'
    | '/payment-methods'
    | '/payments'
    | '/performance'
    | '/profile'
    | '/reports'
    | '/users'
    | '/dashboard/'
    | '/dashboard/area/$areaId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/advertisements'
    | '/areas'
    | '/dealers'
    | '/my-bills'
    | '/packages'
    | '/payment-corrections'
    | '/payment-details'
    | '/payment-methods'
    | '/payments'
    | '/performance'
    | '/profile'
    | '/reports'
    | '/users'
    | '/dashboard'
    | '/dashboard/area/$areaId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/advertisements'
    | '/_authenticated/areas'
    | '/_authenticated/dealers'
    | '/_authenticated/my-bills'
    | '/_authenticated/packages'
    | '/_authenticated/payment-corrections'
    | '/_authenticated/payment-details'
    | '/_authenticated/payment-methods'
    | '/_authenticated/payments'
    | '/_authenticated/performance'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/users'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/area/$areaId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment-methods': {
      id: '/_authenticated/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof AuthenticatedPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment-details': {
      id: '/_authenticated/payment-details'
      path: '/payment-details'
      fullPath: '/payment-details'
      preLoaderRoute: typeof AuthenticatedPaymentDetailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment-corrections': {
      id: '/_authenticated/payment-corrections'
      path: '/payment-corrections'
      fullPath: '/payment-corrections'
      preLoaderRoute: typeof AuthenticatedPaymentCorrectionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/packages': {
      id: '/_authenticated/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof AuthenticatedPackagesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-bills': {
      id: '/_authenticated/my-bills'
      path: '/my-bills'
      fullPath: '/my-bills'
      preLoaderRoute: typeof AuthenticatedMyBillsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dealers': {
      id: '/_authenticated/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof AuthenticatedDealersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/areas': {
      id: '/_authenticated/areas'
      path: '/areas'
      fullPath: '/areas'
      preLoaderRoute: typeof AuthenticatedAreasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/advertisements': {
      id: '/_authenticated/advertisements'
      path: '/advertisements'
      fullPath: '/advertisements'
      preLoaderRoute: typeof AuthenticatedAdvertisementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/area/$areaId': {
      id: '/_authenticated/dashboard/area/$areaId'
      path: '/dashboard/area/$areaId'
      fullPath: '/dashboard/area/$areaId'
      preLoaderRoute: typeof AuthenticatedDashboardAreaAreaIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdvertisementsRoute: typeof AuthenticatedAdvertisementsRoute
  AuthenticatedAreasRoute: typeof AuthenticatedAreasRoute
  AuthenticatedDealersRoute: typeof AuthenticatedDealersRoute
  AuthenticatedMyBillsRoute: typeof AuthenticatedMyBillsRoute
  AuthenticatedPackagesRoute: typeof AuthenticatedPackagesRoute
  AuthenticatedPaymentCorrectionsRoute: typeof AuthenticatedPaymentCorrectionsRoute
  AuthenticatedPaymentDetailsRoute: typeof AuthenticatedPaymentDetailsRoute
  AuthenticatedPaymentMethodsRoute: typeof AuthenticatedPaymentMethodsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAreaAreaIdRoute: typeof AuthenticatedDashboardAreaAreaIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdvertisementsRoute: AuthenticatedAdvertisementsRoute,
  AuthenticatedAreasRoute: AuthenticatedAreasRoute,
  AuthenticatedDealersRoute: AuthenticatedDealersRoute,
  AuthenticatedMyBillsRoute: AuthenticatedMyBillsRoute,
  AuthenticatedPackagesRoute: AuthenticatedPackagesRoute,
  AuthenticatedPaymentCorrectionsRoute: AuthenticatedPaymentCorrectionsRoute,
  AuthenticatedPaymentDetailsRoute: AuthenticatedPaymentDetailsRoute,
  AuthenticatedPaymentMethodsRoute: AuthenticatedPaymentMethodsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardAreaAreaIdRoute: AuthenticatedDashboardAreaAreaIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
